### ISSUE TITLE
RPM for Workalendar

### ISSUE THREAD

**Issue by selwyntheo** [peopledoc/workalendar#126]
Hi,

Is there way to create an Linux RPM using this module?

**Comment by brunobord** [comment]
Hi,

Usually, python-based packages are used inside of a virtualenv, which are isolated from the system packages. Python developers tend not to install python libraries system-wide.

Although, if there's somebody with enough time and knowledge on how to package this, I'd be glad to welcome it.

**Comment by selwyntheo** [comment]
Thanks for your reply. My only intention is have a work around using it an organizational setting. Given the process that is typically in any organization, they tend to have a consistent way to manage packages across all regions like Dev, Test and Prod. Also there is always constraint to using pip install as it access public repositories. Is there a way to do pip install workalendar by have a local download?

We are currently using Linux Red Hat which has python 2.6

**Comment by brunobord** [comment]
> Also there is always constraint to use pip install as it access public repositories. Is there a way to do pip install workalendar by having a local download?

Sure, you can setup your own instance of a package repository. It can host the packages you want/need, mirrored from the canonical PyPI and your own private packages if you need some (your own projects that you don't want to publish on PyPI). The two main projects I know are:

* [devpi](http://doc.devpi.net/latest/)
* [localshop](https://github.com/mvantellingen/localshop)

**Comment by Natim** [comment]
You may also want to use ``pip install --user workalendar``

**Comment by selwyntheo** [comment]
Hi,

When I tried to install workalendar in python 2.6.6, I get this error.

python -c "from workalendar.europe import France"

Traceback (most recent call last):

File "<string>", line 1, in <module>

File "/usr/lib/python2.6/site-packages/workalendar/europe.py", line 3, in <module>

from workalendar.core import WesternCalendar, ChristianMixin, OrthodoxMixin

File "/usr/lib/python2.6/site-packages/workalendar/core.py", line 62

return {day: label for day, label in self.holidays(day.year)

^

Kindly help

**Comment by brunobord** [comment]
I'm deeply sorry, but we won't support Python 2.6 series. workalendar has been tested using Python 2.7 and 3.3.

**Comment by brunobord** [comment]
see: https://github.com/novafloss/workalendar/blob/master/tox.ini#L2

**Comment by toloco** [comment]
Can you close this ticket?
