### ISSUE TITLE
2017 UnitedStates Christmas Day calculation is wrong

### ISSUE THREAD

**Issue by Natim** [peopledoc/workalendar#241]
```
(datetime.date(2017, 12, 24), 'Christmas Eve'),
(datetime.date(2017, 12, 25), 'Christmas Day'),
(datetime.date(2017, 12, 25), 'Christmas Eve (Observed)'),
(datetime.date(2017, 12, 26), 'Christmas Eve (Observed)'),
(datetime.date(2017, 12, 27), 'Christmas Day (Observed)')
```

It should be:

```
(datetime.date(2017, 12, 24), 'Christmas Eve'),
(datetime.date(2017, 12, 25), 'Christmas Day'),
(datetime.date(2017, 12, 25), 'Christmas Eve (Observed)'),
(datetime.date(2017, 12, 26), 'Christmas Day (Observed)')
```

**Comment by brunobord** [comment]
Do you have any link to look at that confirms your implementation? XMas shift for the U.S. was build upon this source:

> When a holiday occurs on Saturday or Sunday, that holiday is shifted to either Friday or Monday

-- https://en.wikipedia.org/wiki/Public_holidays_in_the_United_States

**Comment by Natim** [comment]
Apart from what the US holidays are this year?

I mean that's exactly the rule you are talking about that is wrongly applied here.

**Comment by Natim** [comment]
> When a holiday occurs on Saturday or Sunday, that holiday is shifted to either Friday or Monday

Yes but the 27 is a Wednesday and it shouldn't be present in the list.
