### ISSUE TITLE
Israeli calendar

### ISSUE THREAD

**Issue by tsehori** [peopledoc/workalendar#278]
This isn't trivial since the Israeli holidays (consisting of mainly Jewish holidays) do not belong to the Georgian calendar, but rather the Hebrew calendar.
I think a package such as [pyluach](https://github.com/simlist/pyluach) might be of use here, manipulating Hebrew calendar dates and making Hebrew-Georgian calendar conversions.

docs:

- [https://en.wikipedia.org/wiki/Public_holidays_in_Israel](https://en.wikipedia.org/wiki/Public_holidays_in_Israel)
- [https://en.wikipedia.org/wiki/Hebrew_calendar](https://en.wikipedia.org/wiki/Hebrew_calendar)

**Comment by brunobord** [comment]
Indeed! far from trivial. Last time I've checked, I only found an obscure library that was only available from archive.org, which was far from usable, and I'm not talkin about Python 3 compatibility...

The library you're pointing at looks interesting, and fully compatible with `workalendar` specs (Python 2.7 -> 3.6). That's a good start. I'll add this to the backlog.

**Comment by armona** [comment]
I might be working on it next week, I will send a PR. Looking at the code I had two questions:

* What is the correct approach to holidays which are optional paid leave or unpaid leave?
* Will it be appropriate to implement the holidays which are based on the Jewish calender using `get_variable_days`?

**Comment by tsehori** [comment]
Hey @armona! Just so you know, I've already built a skeleton for the Israeli calendar [right here](https://github.com/tsehori/workalendar/tree/israel). I forked the repo, added a branch 'israel' and added the calendar to every necessary place as mentioned in the [contributing](https://github.com/peopledoc/workalendar/blob/master/CONTRIBUTING.rst) doc. Moreover, I made tests for all of the holidays in 2017 and 2018.
You can see it all in the [commit](https://github.com/tsehori/workalendar/commit/fcf78317c7ee9f25399609a5d1e098b6845a9862). So it's only left to code the calendar itself. :smiley:
Please let me know if and when you work on it, I'd love to be of help if possible!
