### ISSUE TITLE
Reformation Day is now in more states (Germany)

### ISSUE THREAD

**Issue by johnberroa** [peopledoc/workalendar#295]
https://www.timeanddate.com/holidays/germany/reformation-day

Currently there are 9 states that celebrate it, versus the 5 or so of previous years.

**Comment by brunobord** [comment]
mmmm interesting. I'll need to investigate on this, thanks for the information.

**Comment by brunobord** [comment]
information: https://en.wikipedia.org/wiki/Public_holidays_in_Germany

looks like it became a holiday for all states in 2017, but only Four states decided to permanently adopt the Reformation Day as permanent holiday starting of 2018.
This needs further investigation.

**Comment by brunobord** [comment]
Fixed and released [on v3.2.1](https://github.com/peopledoc/workalendar/releases/tag/3.2.1) - happy upgrading!
https://pypi.org/project/workalendar/3.2.1/
