### ISSUE TITLE
Skyfield VS Ephem

### ISSUE THREAD

**Issue by antvig** [peopledoc/workalendar#302]
I'm having trouble installing workalendar since it requires ephem which need to be compiled. (I can't use a precompiled conda package for my purpose.)

I've seen that there is the package [skyfield](https://rhodesmill.org/skyfield/) which does the same than ephem and that doesn't require to be compiled. 

Are you aware of skyfield? If yes, is there a reason why workalendar uses ephem instead of skyfield?

**Comment by antvig** [comment]
Okay, I just looked deeper at skyfield and it is based on Nasa files. So it needs to be downloaded first. I guess my above comment is not relevant.

**Comment by brunobord** [comment]
I agree that somehow it's a bit painful to require development packages to use `ephem`.
I didn't know about Skyfield and it might be interesting to get into it. I'm not very enthusiast about having to download NumPy and other requirements, but if it removes the fact that you need Python-Dev somewhere, why not?

I'll keep your issue in my backlog, for later. thank your for the heads-up!

**Comment by antifa-ev** [comment]
@antvig: What's so difficult here? Just run _python setup.py build_ and then _python setup.py install --optimize=1_

**Comment by smarie** [comment]
On some targets (windows...) recompiling is much less friendly than on others ("let's install windows SDK ! and visual C++ redist ! oh no let's try mingw instead... oh wait the 64 bits version seems to have issues with cpython... oh wait I have to modify a file in the pip distrib to change some includes..." etc.) 

So I understand that some users may just be afraid of compiling python packages on windows. 

However @antvig can you explain why you can not use the precompiled "ephem" conda package in your case ? Thanks !

**Comment by brunobord** [comment]
it looks like calculating solar terms using Skyfield is a bit harder than I first thought... stay tuned, I didn't say my last word!

**Comment by brunobord** [comment]
look, ma! no pyephem! :o)

**Comment by brunobord** [comment]
I'm finally able to present a "PyEphem-free" version of workalendar.
I think this is an important requirement change, so I may need some volunteers to test a pre-version on their machine and tell me if it's okay.
/cc @antvig, @smarie  (or even @antifa-ev) would you be interested?

**Comment by brunobord** [comment]
In case any of you is interested in testing the next Workalendar Release Candidate, here's a procedure you may try to follow: https://github.com/peopledoc/workalendar/issues/398

**Comment by smarie** [comment]
Cool ! I let @antvig have a look if he can as he has been much more involved than I on this topic

**Comment by antvig** [comment]
I will certainly take some time to test it !

**Comment by brunobord** [comment]
@antvig any news on this point?

**Comment by brunobord** [comment]
I'm sorry to have to look a bit pushy, but I'd really want to have at least one more user to confirm that the release candidate is working.
I really wish to move forward on this long-due improvement and I depend on a Windows test (or two, or three, or well...).

So, who can confirm that the RC is working, following the procedure described in #398?

**Comment by antvig** [comment]
I just did at the moment ;)

**Comment by brunobord** [comment]
WOOT!

**Comment by brunobord** [comment]
version 7.0.0 of workalendar has been released and published on PyPI. Upgrade away, to the stars, and beyond!

**Comment by smarie** [comment]
Thanks @brunobord  !
