### ISSUE TITLE
Wrong UnitedKingdom holidays for 2012

### ISSUE THREAD

**Issue by ludsoft** [peopledoc/workalendar#315]
workalendar==4.0.0 from PYPI
python 3.6 on LINUX

Hi, thanks for this library that is exactly what I'm looking for. 
One issue I have is with holidays in the UK that seem to be wrong for years when the government "randomly" decided to add some. The last example is the Queen’s Diamond Jubilee.
Here is the official link: https://www.gov.uk/bank-holidays with 2012 at the end of the page.

The great thing about this year is:
- There is an additional bank holiday on June 5
- The usual Spring bank holiday is **not** the last Monday of May (May 28) but  June 4.

I don't have a complete list (yet) but there are other years with similar holiday like 2002.

Are these holiday something you see being in the scope of workalendar? 
I'll probably fork your repo to manage them anyway so I'm interested to know if you are open to a PR to manage these cases. If it's the case there may be a way you prefer me to go to manage this. 

Bellow the code I run with the missing and wrong date:

    from workalendar.europe import UnitedKingdom 
    cal = UnitedKingdom()
    cal.holidays(2012)

Gives me:
    [(datetime.date(2012, 1, 1), 'New year'),
     (datetime.date(2012, 1, 2), 'New Year shift'),
     (datetime.date(2012, 4, 6), 'Good Friday'),
     (datetime.date(2012, 4, 8), 'Easter Sunday'),
     (datetime.date(2012, 4, 9), 'Easter Monday'),
     (datetime.date(2012, 5, 7), 'Early May Bank Holiday'),
     (datetime.date(2012, 5, 28), 'Spring Bank Holiday'),
     (datetime.date(2012, 8, 27), 'Late Summer Bank Holiday'),
     (datetime.date(2012, 12, 25), 'Christmas Day'),
     (datetime.date(2012, 12, 26), 'Boxing Day')]

Thanks.

**Comment by brunobord** [comment]
Hi,
First of all, thank you for your interest in this library.

> I'll probably fork your repo to manage them anyway so I'm interested to know if you are open to a PR to manage these cases.

Absolutely. It has already happened in other calendars that days would appear for a brief period of time, and then disappear or being replaced by other, change names, etc.
The most recent example I have in mind is the [South African calendar](https://github.com/peopledoc/workalendar/blob/master/workalendar/africa/south_africa.py). As you can see, fixed and variable holidays have evolved.

If you can, please make a PR to solve this issue that can be considered as a bug, that'd be great!

**Comment by ludsoft** [comment]
I've made the pull request, let me know if there is anything I need to change.

**Comment by brunobord** [comment]
Your patch is part of the v4.1.0, released and published on PyPI. Enjoy!
