### ISSUE TITLE
Russia - Day of Unity

### ISSUE THREAD

**Issue by alexitkes** [peopledoc/workalendar#317]
Day of Unity in Russia is celebrated on Nov, 4 (https://en.wikipedia.org/wiki/Unity_Day_(Russia)), but this code seems to put it on Nov 5.
```
(11, 5, "Day of Unity")
```

If I understand it properly, this line should be changed to
```
(11, 4, "Day of Unity")
```

I'll do it if needed. Should I?

**Comment by brunobord** [comment]
it's probably a typo or an error. I'll take care.

**Comment by brunobord** [comment]
Your patch is part of the v4.1.0, released and published on PyPI. Enjoy!
