### ISSUE TITLE
UK - get_working_days_delta not calculating correctly

### ISSUE THREAD

**Issue by zeetaros** [peopledoc/workalendar#323]
Example1: counting number of working days in August 2018
`united_kingdom.UnitedKingdom().get_working_days_delta(datetime(2018, 8, 1),datetime(2018, 8, 31))`
returns 21, which should be 22.

Example2: counting number of working days in October 2018
`united_kingdom.UnitedKingdom().get_working_days_delta(datetime(2018, 10, 1),datetime(2018, 10, 31))`
returns 22, which is again 1 day less than it should be.

Thanks.

**Comment by brunobord** [comment]
I'll have a look as soon as possible. But in the meantime, could you confirm that it isn't it a problem of intervals? the delta function doesn't include the starting day in the number of days

```
delta(d, d) == 0
delta(d, d+1) == 1  # etc
```

Could you please describe in the comments a more detailed way on how you did your calculations? That'd help me figure out where the problem is before trying to solve it.
Thx.

**Comment by brunobord** [comment]
Hello,
I've had a brief look and here the code that would explain my previous comment:

```python
from datetime import datetime, timedelta
from workalendar.europe import UnitedKingdom
cal = UnitedKingdom()

start, end = datetime(2018, 8, 1), datetime(2018, 8, 31)
current = start
count = 0
while current <= end:
    print(current, cal.is_working_day(current), count)
    current += timedelta(days=1)
    if cal.is_working_day(current):
        count += 1

print(cal.get_working_days_delta(start, end), count)
```

result:
```
2018-08-01 00:00:00 True 0
2018-08-02 00:00:00 True 1
2018-08-03 00:00:00 True 2
2018-08-04 00:00:00 False 2
2018-08-05 00:00:00 False 2
2018-08-06 00:00:00 True 3
2018-08-07 00:00:00 True 4
2018-08-08 00:00:00 True 5
2018-08-09 00:00:00 True 6
2018-08-10 00:00:00 True 7
2018-08-11 00:00:00 False 7
2018-08-12 00:00:00 False 7
2018-08-13 00:00:00 True 8
2018-08-14 00:00:00 True 9
2018-08-15 00:00:00 True 10
2018-08-16 00:00:00 True 11
2018-08-17 00:00:00 True 12
2018-08-18 00:00:00 False 12
2018-08-19 00:00:00 False 12
2018-08-20 00:00:00 True 13
2018-08-21 00:00:00 True 14
2018-08-22 00:00:00 True 15
2018-08-23 00:00:00 True 16
2018-08-24 00:00:00 True 17
2018-08-25 00:00:00 False 17
2018-08-26 00:00:00 False 17
2018-08-27 00:00:00 False 17
2018-08-28 00:00:00 True 18
2018-08-29 00:00:00 True 19
2018-08-30 00:00:00 True 20
2018-08-31 00:00:00 True 21
21 21
```

As you can see, the delta between "today" and "today" is 0 (zero), while between "today" and "tomorrow" is 1 if those two days are working days, and so on.

My guess is that you wanted to calculate *"how many working days are there in August 2018?"*, while the ``get_working_days_delta`` will calculate *"how many working days are there after 1st of August to get to the last day of August?"*

So, the number of working days between 2018-08-01 and 2018-08-31 is 21, while effectively 21, while you have 22 working days in total for this month.

If you wanted to count how many working days there are in August 2018, here's how I'd do it:

```python
from datetime import datetime, timedelta
from workalendar.europe import UnitedKingdom
cal = UnitedKingdom()
days = (datetime(2018, 8, x) for x in range(1, 32))
days = map(lambda day: cal.is_working_day(day), days)
total = sum(days)
```

(taking advantage that when you do the sum of booleans, ``True`` is considered as a 1 and ``False`` as a 0.

I'm going to close that comment, for in my opinion, the behaviour of ``get_working_days_delta()`` behaves as expected. In the meantime, if you think that workalendar needs a method to compute how many working days there are in a month, [do not hesitate to contribute and propose a pull-request](https://github.com/peopledoc/workalendar/blob/master/CONTRIBUTING.rst), I'd be happy to review it.

**Comment by zeetaros** [comment]
Hi Bruno, thanks for the detailed clarification! Yep this is very helpful and sorry for my late response.

**Comment by brunobord** [comment]
You're very welcome, and no worries, I *had* to figured it out anyways :o)
