### ISSUE TITLE
America:  Cayman Island calendar

### ISSUE THREAD

**Issue by toloco** [peopledoc/workalendar#328]
Add support for Cayman Island calendar

As many banks and institutions are working with Cayman Islands funds or banks I believe this will be very useful and help to rocket this library at the corporate level.

**Comment by brunobord** [comment]
I wouldn't have thought about this library this "corporate" way, but thank you for your suggestion.
I'll add this new calendar as soon as I can.

Or maybe you could try by opening a pull-request? It's [documented here](https://github.com/peopledoc/workalendar/blob/master/CONTRIBUTING.rst#adding-new-calendars) and I'd be happy to review it!

For the record: https://en.wikipedia.org/wiki/Public_holidays_in_the_Cayman_Islands

**Comment by Natim** [comment]
The title says America but as far as I know Cayman's Island are a British Overseas Territory. Shall I put them in the america.py file or in the eu.py file? :rocket:

**Comment by toloco** [comment]
I said America as it sounds more geographically correct, but your point makes more sense.

**Comment by brunobord** [comment]
mmmm both? j/k
I'd be tempted to say "europe" namespace, since it's attached to the British Crown.

**Comment by toloco** [comment]
By the way, do you get movable public holidays hardcoded or using something else? like parsing a government website

**Comment by Natim** [comment]
I started something in PR #329 what bother's me the most is the Queen Birthday. I will move it in europe.

**Comment by toloco** [comment]
oh sweet, thanks I was just adding it

**Comment by Natim** [comment]
Sorry about that :confused:

**Comment by Natim** [comment]
> For the record: https://en.wikipedia.org/wiki/Public_holidays_in_the_Cayman_Islands

http://www.gov.ky/portal/page/portal/cighome/publicholidays

**Comment by brunobord** [comment]
merged, tagged and released: https://github.com/peopledoc/workalendar/releases/tag/4.2.0

[Also available on PyPI](https://pypi.org/project/workalendar/4.2.0/). Enjoy!
