### ISSUE TITLE
UK calendar missing one-off holiday for royal family wedding in 2010

### ISSUE THREAD

**Issue by richardbarran** [peopledoc/workalendar#336]
The UK calendar already lists 2 one-off public holidays for events related to the royal family. It is however missing [a public holiday on 29th April 2010 that marked a wedding in the royal family](https://www.bbc.com/news/uk-11818049).

**Comment by Natim** [comment]
Good catch, would you be willing to make a pull-request to fix this miss?

**Comment by richardbarran** [comment]
Will do!

**Comment by brunobord** [comment]
[released](https://github.com/peopledoc/workalendar/releases/tag/4.3.0) and [available on PyPI](https://pypi.org/project/workalendar/4.3.0/).
