### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by eccodolf** [peopledoc/workalendar#348]
workalendar depend on ephem which was deprecated.
Last python version of pre-built ephem wheel is 3.4 and one must compile this package from source for newer python. But it requires VC++14. For many machines behind firewall it's a bit complicated to get older compiler versions.

**Comment by brunobord** [comment]
Currently looking at [Skyfield](https://rhodesmill.org/skyfield/)
It has already been raised that this dependency was causing a problem.
But Skyfield has other issues, essentially that it would require to embed 17MB of data files. I'm not sure of the right way to do that, if it could be integrated in the package (which would cause it to be bigger), or to load them via the internet when you're installing the package (eeek ugly setup.py), or any better solution.

refs: https://github.com/peopledoc/workalendar/issues/302

**Comment by brunobord** [comment]
I'm finally able to present a "PyEphem-free" version of workalendar.
I think this is an important requirement change, so I may need some volunteers to test a pre-version on their machine and tell me if it's okay.
/cc @eccodolf or @linker81 would you be interested?

**Comment by brunobord** [comment]
In case any of you is interested in testing the next Workalendar Release Candidate, here's a procedure you may try to follow: https://github.com/peopledoc/workalendar/issues/398

**Comment by brunobord** [comment]
I'm sorry to have to look a bit pushy, but I'd really want to have at least one more user to confirm that the release candidate is working.
I really wish to move forward on this long-due improvement and I depend on a Windows test (or two, or three, or well...).

So, who can confirm that the RC is working, following the procedure described in #398?

**Comment by brunobord** [comment]
@antvig made a successful test, I'm moving forward.

**Comment by brunobord** [comment]
version 7.0.0 of workalendar has been released and published on PyPI. Upgrade away, to the stars, and beyond!
