### ISSUE TITLE
Malaysia Thaipusam 2019

### ISSUE THREAD

**Issue by burlak** [peopledoc/workalendar#354]
Hi!

Please, add        2019: date(2019, 1, 21) to MSIA_THAIPUSAM

Now i get error KeyError: 'Missing date for Malaysia Thaipusam for year: 2019'

**Comment by brunobord** [comment]
hello. Sure, I'll add it as soon as I can. While we're at it, do we know the date of next year's Malaysia Thaipusam already? (to add it along, and prevent this inaccuracy in 2020)

**Comment by burlak** [comment]
Thank you so much!

Saturday
, February 8
Thaipusam 2020 in Malaysia

I can do it myself, if you grant me access to your project.

**Comment by brunobord** [comment]
> I can do it myself, if you grant me access to your project.

You're not required to have access. Just fork this project, create a new branch, patch it, and [propose a pull-request!](https://help.github.com/en/articles/about-pull-requests)

**Comment by brunobord** [comment]
All right, don't bother. I've got some time in my hands to work on this. Expect a bugfix release today :o)

**Comment by brunobord** [comment]
Version 5.0.0 pushed, released and available on PyPI: https://pypi.org/project/workalendar/5.0.0/
