### ISSUE TITLE
Build Python3 wheels

### ISSUE THREAD

**Issue by brunobord** [peopledoc/workalendar#366]
This needs to be scripted:

* get only releases that are/were compatible with Python3
* eventually check that we can build them using Python 3.6, even if they weren't Py3.6 compatible.
* don't forget to remove the `build/` repository before rebuilding (following @ewjoachim's advice)
* push to PyPI

**Comment by ewjoachim** [comment]
(if you're building wheels for py3 only, then you won't need the "universal = True" that everyone puts everywhere)

**Comment by brunobord** [comment]
here's the script I've used (yes, it could've been bash, but I never remember how to make a loop):

```python
from shell import shell
from distutils.version import StrictVersion

result = shell('git tag')
tags = result.output()
tags = filter(lambda x: not x.startswith('v'), tags)  # That was a mistake
tags = filter(lambda x: StrictVersion(x) >= StrictVersion("1.0.0"), tags)

for tag in tags:
    print(tag)
    shell(f'git checkout {tag}')
    shell('rm -Rf build/')
    result = shell('python setup.py bdist_wheel')
    if result.code:
        print(result.errors())

shell('git checkout master')

```

**Comment by brunobord** [comment]
currently uploading every wheel from 1.0.0 to the latest release without any Py3 wheel.

**Comment by ewjoachim** [comment]
:clap:
