### ISSUE TITLE
Turkey calendar

### ISSUE THREAD

**Issue by brunobord** [peopledoc/workalendar#371]
As a follow up to @tayyipgoren's work and information. We need to:

- [x] Implement the ability to add a delta to islamic days, depending on the country context, or even the year (since the beginning of the Ramadan is subject to arbitrary decisions for example). By default, no delta is added.
- [x] Turkey's calendar is subject to substract one day to each Islamic holidays.
- [x] Rebase @tayyipgoren branch to align with the latest master, squash extra commits etc,
- [x] Add tests for the shifting New Year's Day if it happens on Sunday.
- [ ] Question for @tayyipgoren : could you please confirm that the "WEEKEND_DAYS" are Saturday and Sunday?

**Comment by brunobord** [comment]
Hello, @tayyipgoren I've got a question for you, can you confirm that the weekend days in Turkey are Saturday and Sunday? Many thanks.

**Comment by tayyipgoren** [comment]
Yes indeed Saturday and Sunday are holiday in Turkey.

**Comment by brunobord** [comment]
Turkey calendar is now available on the v5.1.0, now on PyPI: https://pypi.org/project/workalendar/5.1.0/
Enjoy!
