### ISSUE TITLE
UK change to 2020 early May bank holiday

### ISSUE THREAD

**Issue by ShaheedHaque** [peopledoc/workalendar#381]
The UK early May bank holiday for 2020 is changing from the expected date to 8-May:

- [Official record from UK government site](https://www.gov.uk/bank-holidays)
- [Background info from BBC](https://www.bbc.co.uk/news/uk-48565417)

I'd like to request this be added please.

**Comment by brunobord** [comment]
Thank you for this report. I'll try to fix this as soon as I can and will keep you informed when it's released

**Comment by ShaheedHaque** [comment]
Perfect; thanks!

**Comment by brunobord** [comment]
The [v5.2.1](https://github.com/peopledoc/workalendar/releases/tag/5.2.1) was released, [pushed to PyPI and ready to be installed](https://pypi.org/project/workalendar/5.2.1/) with the fix you've suggested.

Enjoy!

**Comment by ShaheedHaque** [comment]
Thanks a lot!
