### ISSUE TITLE
Denmark adjustments

### ISSUE THREAD

**Issue by KidkArolis** [peopledoc/workalendar#386]
Can I open a PR removing the following from Denmark holidays?

Jun 5 | Constitution Day
Dec 24 | Christmas Eve
Dec 31 | New Year's Eve

According to these source, those are not officially non working days, they're only Observances:
https://publicholidays.dk/2019-dates/
https://www.timeanddate.com/holidays/denmark/

**Comment by brunobord** [comment]
seems that you are absolutely right ; Denmark calendar is wrong.

as long as you follow the [contributing guidelines](https://github.com/peopledoc/workalendar/blob/master/contributing.md), tick [all the relevant checkboxes when you write your PR](https://raw.githubusercontent.com/peopledoc/workalendar/master/.github/PULL_REQUEST_TEMPLATE.md), you should be fine.

If you need some help, don't hesitate :o)

**Comment by brunobord** [comment]
[version 5.2.2](https://github.com/peopledoc/workalendar/releases/tag/5.2.2) (sorry about the pun, couldn't resist) has been [released and pushed on PyPI](https://pypi.org/project/workalendar/5.2.2/) with your lovely patch.
Enjoy!
