### ISSUE TITLE
Problem with duration calculation

### ISSUE THREAD

**Issue by Querdos** [peopledoc/workalendar#393]
Hello,

First of all, thank you for developping such a library, it's really useful in some situations...

I'm currently playing with it and I think I found an issue that can be bothering... ^^

I'm using the `calendar.get_working_days_delta` method, and I found an interesting problem (maybe not a bug? You tell me :) )

Steps:
*  I want to compute working days between two following dates (let's say `31/12/2018 00:01` and `01/01/2019 19:03`) and the result is not correct... I should have 1 working day (and so in my case 11hours of working time, but not the point here) but I actually get 0 working days...

What is actually working:
*  I want to compute working days between two following dates (let's say `01/01/2019 00:01` and `02/01/2019`) and here the result is ok, I'm having 1 working day (and so in my case 11 hours of working time, but again not the point here).

Environment:
*  `python3.7.4`
*  `workalendar==5.0.3` (Pypi)

How to reproduce the situation:
```python
from dateutil.parser import parse
from workalendar.europe import France

cal = France()

# First use case: it's ok, everything is fine
d_1 = parse('01/01/2019 00:01', dayfirst=True)
d_2 = parse('02/01/2019 19:01', dayfirst=True)

print(f'{d_1} is a working day? {cal.is_working_day(d_1)}')
print(f'{d_2} is a working day? {cal.is_working_day(d_2)}')
print(f'Number of working days between: {cal.get_working_days_delta(d_1, d_2)}')

# Second use case: not ok
d_1 = parse('31/12/2018 00:01', dayfirst=True)
d_2 = parse('01/01/2019 19:01', dayfirst=True)

print(f'{d_1} is a working day? {cal.is_working_day(d_1)}')
print(f'{d_2} is a working day? {cal.is_working_day(d_2)}')
print(f'Number of working days between: {cal.get_working_days_delta(d_1, d_2)}')
```

Output:
```
2019-01-01 00:01:00 is a working day? False
2019-01-02 19:01:00 is a working day? True
Number of working days between: 1

2018-12-31 00:01:00 is a working day? True
2019-01-01 19:01:00 is a working day? False
Number of working days between: 0
```

**Comment by brunobord** [comment]
I think it has something to do with the fact that the two starting and ending dates are not on the same year.
I'll investigate this bug and will get back to you as soon as I can - but don't expect it too fast, it's summer time ;o)

**Comment by Querdos** [comment]
Sorry but unfortunately not related to the same year, I just ran another test:
```python
from dateutil.parser import parse
from workalendar.europe import France

cal = France()

# First use case: not ok
d_1 = parse('09/05/2018 00:01', dayfirst=True)
d_2 = parse('10/05/2018 19:01', dayfirst=True)

print(f'{d_1} ({d_1.strftime("%A")}) is a working day? {cal.is_working_day(d_1)}')
print(f'{d_2} ({d_2.strftime("%A")}) is a working day? {cal.is_working_day(d_2)}')
print(f'Number of working days between: {cal.get_working_days_delta(d_1, d_2)}')

# Second use case: ok
d_1 = parse('10/05/2018 00:01', dayfirst=True)
d_2 = parse('11/05/2018 19:01', dayfirst=True)

print(f'{d_1} ({d_1.strftime("%A")}) is a working day? {cal.is_working_day(d_1)}')
print(f'{d_2} ({d_1.strftime("%A")}) is a working day? {cal.is_working_day(d_2)}')
print(f'Number of working days between: {cal.get_working_days_delta(d_1, d_2)}')
```

Output:
```
2018-05-09 00:01:00 (Wednesday) is a working day? True
2018-05-10 19:01:00 (Thursday) is a working day? False
Number of working days between: 0

2018-05-10 00:01:00 (Thursday) is a working day? False
2018-05-11 19:01:00 (Thursday) is a working day? True
Number of working days between: 1
```

**Comment by brunobord** [comment]
ah. Here it's different, indeed. This one looks quite similar to #323 

The function goes as follows:

```python
count = 0
while start < end:
    start += timedelta(days=1)
    if self.is_working_day(start):
        count += 1
return count
```

As you can see here, if the day after your start is not a working day, `count` will remain set to `0`.

At the moment there's no option to decide whether you're counting the starting day in the delta or not.  Maybe that's an idea for a contribution.
If this behaviour doesn't look obvious to users, it means it's not intuitive, so I guess it would be cool to add this option.

**Comment by Querdos** [comment]
Let's start contributing then :)

**Comment by brunobord** [comment]
released and published on PyPI: https://pypi.org/project/workalendar/6.0.0/ Enjoy!
