### ISSUE TITLE
Republic Day of Turkey

### ISSUE THREAD

**Issue by mhmtozc** [peopledoc/workalendar#399]
Hi, when I use this library I realize that Republic Day of Turkey states as 9/29 (September 29). It is wrong. It must be October 29 or 10/29. 

Could you please fix it. Thanks...

https://www.google.com.tr/search?sxsrf=ACYBGNSSfT46iCPeo4FZoLhuk7Mo0fMGdA%3A1568718966328&source=hp&ei=dsCAXbyaEpmAk74P-r6muAc&q=29+ekim+1923&oq=29+ekim+&gs_l=psy-ab.3.0.0i131l5j0j0i131j0j0i131j0.920.3366..5582...0.0..0.131.989.0j8......0....1..gws-wiz.......0i131i70i257.zChEqS8wXhM

**Comment by Natim** [comment]
@mhmtozc thank you for noticing. Would you be willing to send a Pull-Request with a fix?

**Comment by mhmtozc** [comment]
I am sorry, I am new on Github and Python. So I do not know how can I fix this? I just run the codes I found for now.

**Comment by Natim** [comment]
Ok no problem, feel free to have a look at the PR I filed at #400

**Comment by brunobord** [comment]
Merged the PR. I'm going to make a bugfix release, stay tuned.

**Comment by brunobord** [comment]
v6.0.1 was released and published on PyPI.

* https://pypi.org/project/workalendar/
* https://github.com/peopledoc/workalendar/releases/tag/6.0.1

Thank you very much to both of you, it's this kind of contribution that's building workalendar the way it is! :o)

**Comment by mhmtozc** [comment]
Experienced such a collaboration my first day on GitHub. Thank you all...
