### ISSUE TITLE
Geneva Calendar

### ISSUE THREAD

**Issue by cw-intellineers** [peopledoc/workalendar#420]
The calendar in Geneva is the same as the Swiss calendar, with the following exceptions:
* Berchtold's day is not celebrated (2.1)
* They celebrate two additional holidays:
   * Jeûne genevois or Genevan Fast: Thursday following the first Sunday of September
   * Creation of the Geneva Republic: Celebrated on the 31.12

I will create a PR soon.

**Comment by cw-intellineers** [comment]
I've created a pull request, which is ready to be merged (#421)

**Comment by brunobord** [comment]
Geneva calendar has been added to the 7.1.1 release and is available from PyPI. Happy upgrading, and thank you for this cool contribution!
