### ISSUE TITLE
Missing Singapore Deepavali for 2021

### ISSUE THREAD

**Issue by jack-pace** [peopledoc/workalendar#432]
This website suggests that it is Thursday 4th November 2021.
https://publicholidays.sg/deepavali/

Without this hardcoded date I am unable to use `workalendar` to find out _any_ holidays in Singapore for 2021!

 I am using python 3.6 and workalendar 7.1.1.
### Example
```python
import datetime
import workalendar
calendar = workalendar.registry.registry.get_calendar_class("SG")()
calendar.is_holiday(datetime.date(2021, 1, 1))
```
```
.../site-packages/workalendar/core.py:720: UserWarning: Please take note that, due to arbitrary decisions, this Islamic calendar computation may be wrong.
  warnings.warn('Please take note that, due to arbitrary decisions, '
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
...   ...   ...   ...   ...   ...   ...   ...   ...   ...   ...
KeyError: 'Missing date for Singapore Deepavali for year: 2021'
```

**Comment by jack-pace** [comment]
Ideally we'd be able to suppress this error with a flag if we didn't mind about missing Deepavali or other holidays implemented in this way.
For example:
```python
import datetime
import workalendar
calendar = workalendar.registry.registry.get_calendar_class("SG")()
calendar.is_holiday(datetime.date(2021, 1, 1), best_effort=True)  # Doesn't raise if 
```
Does anyone know what would be involved to achieve this? Or have any other opinions / suggestions?

**Comment by brunobord** [comment]
closed by merging #433 ; release is on its way.

**Comment by brunobord** [comment]
version 7.2.0 was [just released](https://github.com/peopledoc/workalendar/releases/tag/7.2.0), the packages were [uploaded on PyPI](https://pypi.org/project/workalendar/7.2.0/), which includes your contribution. Happy upgrading!

**Comment by jack-pace** [comment]
Thank you very much!
