### ISSUE TITLE
Drop Python 2 support

### ISSUE THREAD

**Issue by brunobord** [peopledoc/workalendar#442]
This is a subtask of #330

- [x] remove ``from __future__``
- [x] remove ``coding`` headers
- [x] Look after ``super()`` methods.
- [x] Relative imports
- [x] class don't need to inherit from `object`
- [x] Remove the ``skipIf(PY2)`` skipped tests in Scotland and USA tests
- [x] Update documentation regarding relative/absolute imports

**Comment by Natim** [comment]
Refs #443
