### ISSUE TITLE
Can I set Saturday as working day as well?

### ISSUE THREAD

**Issue by leopet321** [peopledoc/workalendar#450]
I am new to program. I saw that I can use `extra_working_days` in the `is_working_day` to add every saturday into the calendar as working day(are there any sample of how to use this function?) but it will be tedious to do this task. Are there any  easier way to just add saturday to be working day?

**Comment by brunobord** [comment]
Hi.

First of all, welcome to this project.

> Are there any easier way to just add saturday to be working day?

There's probably an easier way that calculating every saturday of a year and add them to the `extra_working_days`, yes.

Let's imagine that your calendar is `France` (but that would work with any other calendar).
Last saturday (Jan 11th) was not a working day:

```python
>>> from workalendar.europe import France
>>> from datetime import date
>>> cal_france = France()
>>> saturday = date(2020, 1, 11)
>>> cal_france.is_working_day(saturday)
False
```

Now let's define a new France class, that inherits from `France`.

```python
from workalendar.core import SUN
class FranceWithSaturdays(France):

    def get_weekend_days(self):
        return (SUN,)
```

Let's say that this class is in a module you can import from the rest of your code. Now you can do this:

```python
>>> from my.own.module import FranceWithSaturdays
>>> from datetime import date
>>> cal_france = FranceWithSaturdays()
>>> saturday = date(2020, 1, 11)
>>> cal_france.is_working_day(saturday)
True
```

This class will inherit all the France holidays, but would also add saturdays in every computation of number of working days between two dates, etc.

Does that answer your question?

**Comment by brunobord** [comment]
Oh and one more thing: you can overwrite the `get_weekend_days` methode, but mind you: it must return a tuple.

refs: https://github.com/peopledoc/workalendar/blob/9b9bbbb02d9f5fe6deb95dd0d64622c1910da544/workalendar/core.py#L105-L116

**Comment by brunobord** [comment]
@leopet321 I saw you reacted using :+1: can I close your issue, then?

**Comment by leopet321** [comment]
> @leopet321 I saw you reacted using 👍 can I close your issue, then?

yes. thanks for your quick respond
