### ISSUE TITLE
Date and/or holiday name modification required? (Subdivision: US-GA / Year: 2020)

### ISSUE THREAD

**Issue by jbroudou** [peopledoc/workalendar#451]
It appears from https://georgia.gov/popular-topic/state-holidays that in 2020 in Georgia, "State Holiday" is 2020-04-10 (Friday).

Your project is currently recording Confederate Memorial Day on 2020-04-27 (Monday), and does not record "State Holiday" on 2020-04-10 (Friday).

It would be great if could investigate and determine what, if any changes, are necessary to your project for this holiday. Thanks in advance!

**Comment by brunobord** [comment]
mmmm... I see, it looks like we need to investigate. Thank you for the input!

**Comment by brunobord** [comment]
Live from my investigation.

Sources:

* Wikipedia page: https://en.wikipedia.org/wiki/Holidays_with_paid_time_off_in_the_United_States#Georgia
* Georgia State: https://georgia.gov/popular-topic/state-holidays
* 2020 holiday Memo from the governor: http://team.georgia.gov/wp-content/uploads/2019/07/2020-State-Holidays-07.15.19.pdf
* 2019 holiday memo: http://team.georgia.gov/wp-content/uploads/2018/10/2019-State-Holidays-Memo-07.18.18.pdf
* 2018 holiday memo: http://team.georgia.gov/wp-content/uploads/2017/07/2018-State-Holidays-memo-07.12.17.pdf

**Comment by brunobord** [comment]
It's becoming more and more confusing... Now I have a headache, I think I'm going to need a lot more time to fix this.

Other sources: https://web.archive.org/web/20170801000000*/https://georgia.gov/popular-topic/state-holidays

**Comment by brunobord** [comment]
@jbroudou FYI: https://github.com/peopledoc/workalendar/pull/457

**Comment by brunobord** [comment]
Release 8.0.2 published on PyPI. Upgrade away!
