### ISSUE TITLE
Missing days and not relevant days in the Israeli calendar

### ISSUE THREAD

**Issue by elaav** [peopledoc/workalendar#461]
There are two issues in the Israeli calendar:
* Working days holidays are confused with non-working days holidays (Purim, Hol Hamoed Sukkot, Gdalia Fast)
* The holidays' eves are missing. People in Israel usually won't work on a holiday eve, and if they will it will be only until noonish.

see the holidays here (the non-working holidays are only those with a blank observance):
https://www.qppstudio.net/publicholidays2020/israel.htm

so for 2020 we should remove:
date(2020, 9, 21),  # Gdalia Fast
date(2020, 3, 10),  # Purim
date(2020, 3, 11),  # Purim
date(2020, 10, 4),  # Hol Hamoed Sukkot
date(2020, 10, 5),  # Hol Hamoed Sukkot
date(2020, 10, 6),  # Hol Hamoed Sukkot
date(2020, 10, 7),  # Hol Hamoed Sukkot
date(2020, 10, 8),  # Hol Hamoed Sukkot

and add:
date(2020, 9, 18),  # Rosh Hashana Eve
date(2020, 9, 27),  # Kippur Eve
date(2020, 10, 2),  # Sukot A Eve
date(2020, 10, 9),  # Sukot B Eve
date(2020, 4, 8),  # Pesach A Eve
date(2020, 4, 14),  # Pesach B Eve
date(2020, 4, 28),  # Independence Day Eve
date(2020, 5, 28),  # Shavuot Eve

**Comment by brunobord** [comment]
Version 8.1.0 was released and pushed to PyPI. Upgrade away!
