### ISSUE TITLE
BrazilBankCalendar ignore `include_*` flags

### ISSUE THREAD

**Issue by iurisilvio** [peopledoc/workalendar#474]
https://github.com/peopledoc/workalendar/blob/master/workalendar/america/brazil.py#L605-L631

I want to extend `BrazilBankCalendar` to don't consider `ash_wednesday`, but I had to rewrite the `get_variable_days` for that.

Works for me, but could be better.

**Comment by brunobord** [comment]
Release pushed on PyPI. Happy upgrade! https://pypi.org/project/workalendar/8.2.1/
