### ISSUE TITLE
America / Argentina has errors in the names of the holidays

### ISSUE THREAD

**Issue by cjadeveloper** [peopledoc/workalendar#476]
Firts of all, Good Job! I'm testing the last version of `workalander` and you have a mistake with the holiday's names [here](https://github.com/peopledoc/workalendar/blob/master/workalendar/america/argentina.py#L19) and [here](https://github.com/peopledoc/workalendar/blob/master/workalendar/america/argentina.py#L20)

The correct names are: 
```python
(3, 24, "Día Nacional de la Memoria por la Verdad y la Justicia"),
(4, 2, "Día del Veterano y de los Caídos en la Guerra de Malvinas."),
```

In addition, the holiday of April 2 was transferred to Tuesday, March 31, 2020, for the only time, due to mandatory and preventive isolation throughout the country. [Decree 297/2020](https://www.boletinoficial.gob.ar/detalleAviso/primera/227042/20200320)

So [this](https://github.com/peopledoc/workalendar/blob/master/workalendar/america/argentina.py#L20) would be, for this year, as follows:

```python
(31, 3, "Día del Veterano y de los Caídos en la Guerra de Malvinas."),
```

[oficial source](https://www.argentina.gob.ar/interior/feriados-nacionales-2020)

If you want, I can do a PR with the corrections and add the remaining fixed holidays

**Comment by brunobord** [comment]
If you can handle this PR, I'd be glad to review it and integrate it as fast as possible.
Please make sure that the exceptional transfers only happen for the only years concerned by the exceptions.
I'll watch this space ;o)

**Comment by brunobord** [comment]
all right, taking over this issue. I'll try to fix this today.

**Comment by brunobord** [comment]
Latest version was uploaded to PyPI, including this fix. Happy upgrading!
