### ISSUE TITLE
duplicated holiday

### ISSUE THREAD

**Issue by greatfung** [peopledoc/workalendar#496]
Hi Bruno, 

Sorry for overlooking on my testing for last request #482 , there are minor issues:

>>> from workalendar.asia import HongKongBank
>>> cal=HongKongBank()
>>> cal.holidays(2021):
(datetime.date(2021, 1, 1), 'New year')
(datetime.date(2021, 2, 12), "Chinese Lunar New Year's Day")
(datetime.date(2021, 2, 13), 'Second day of Chinese Lunar New Year')
(datetime.date(2021, 2, 14), 'Third day of Chinese Lunar New Year')
_(datetime.date(2021, 2, 15), 'Third day of Chinese Lunar New Year (shift)')
(datetime.date(2021, 2, 15), 'Third day of Chinese Lunar New Year shift')_
(datetime.date(2021, 4, 2), 'Good Friday')
(datetime.date(2021, 4, 3), 'Easter Saturday')
**(datetime.date(2021, 4, 4), 'Ching Ming Festival')
(datetime.date(2021, 4, 5), 'Ching Ming Festival (shift)')
(datetime.date(2021, 4, 5), 'Ching Ming Festival shift')
(datetime.date(2021, 4, 5), 'Easter Monday')**
(datetime.date(2021, 5, 1), 'Labour Day')
(datetime.date(2021, 5, 19), "Buddha's Birthday")
(datetime.date(2021, 6, 14), 'Tuen Ng Festival')
(datetime.date(2021, 7, 1), 'SAR Establishment Day')
(datetime.date(2021, 9, 22), 'Day After Mid-Autumn Festival')
(datetime.date(2021, 10, 1), 'National Day')
(datetime.date(2021, 10, 14), 'Chung Yeung Festival')
(datetime.date(2021, 12, 25), 'Christmas Day')
(datetime.date(2021, 12, 26), 'Boxing Day')
_(datetime.date(2021, 12, 27), 'Boxing Day (shift)')
(datetime.date(2021, 12, 27), 'Boxing Day shift')_

1. the holiday shift are duplicated, one with brackets and one without "(shift) vs shift", this doesn't affect the correctness of holiday calculation, but the number of holidays count 
2. for overlapped holiday shifting, 2021/4/2-5 Easter holiday & 4/4 Ching Ming Festival, although 2021 holidays are not yet announced/confirmed, from my past experience, 2021/4/6 is definitely a public holiday, Ching Ming Festival shift will be further shifted since 4/5 is already a holiday

**Comment by brunobord** [comment]
I think I can try to fix the duplicated shift (which also happens for Boxing Day, there must be a mishandling on this side), but we'll have to wait a bit before solving the 2021 holidays.

**Comment by greatfung** [comment]
Sure Bruno, thanks for your effort.

Btw, fyi,  the 2021 hk holidays have just been announced officially
https://www.gov.hk/en/about/abouthk/holiday/2021.htm

**Comment by brunobord** [comment]
version 9.0.1 was released and is available from PyPI. Happy upgrading!
