### ISSUE TITLE
Israel Holidays Performance Issue

### ISSUE THREAD

**Issue by elaav** [peopledoc/workalendar#498]
While integrating the workalendar library to some of our projects we detected some performance issues with the Israel calendar.

We are using the `is_holiday` method, and while looking into the Israel code I saw that the way to retrieve the Israel holidays list is inefficient, since it is checking every day in a year instead of using some holidays list.

**Comment by brunobord** [comment]
solved by #499. I'll ping here when the release will be available. Stay tuned!

**Comment by brunobord** [comment]
version 9.0.1 was released and is available from PyPI. Happy upgrading!
