### ISSUE TITLE
Croatia new National Holiday and Independence day moved

### ISSUE THREAD

**Issue by davidpodrebarac** [peopledoc/workalendar#515]
Hello,

there were some changes in 2019. for national holidays in Croatia. Holidays listed [here](https://www.officeholidays.com/countries/croatia/2020) are correct. This means that the following changes need to be made:
1. `Statehood day` needs to be moved from Jun 25 to May 30,
2. A new holiday named `Remembrance Day` must be added on Nov 18.

**Comment by brunobord** [comment]
Thank you for the information

**Comment by brunobord** [comment]
@davidpodrebarac  Wikipedias's article says the change happened in 2020, but the 2019 holidays were as before. I'll try to check with other sources, but do you confirm?

**Comment by brunobord** [comment]
If we compare: https://www.officeholidays.com/countries/croatia/2020 with https://www.officeholidays.com/countries/croatia/2019 it's clear:

* 2019's Statehood day happened on Jun 25 (as before),
* Remembrance day wasn't celebrated in 2019.

I'll implement the change accordingly.

**Comment by brunobord** [comment]
Version 10.2.0 was released and published on PyPI, including bugfixes for Croatia calendar.
Have fun upgrading!

* https://github.com/peopledoc/workalendar/releases/tag/10.2.0
* https://pypi.org/project/workalendar/10.2.0/
