### ISSUE TITLE
test_ical_export fails on Windows

### ISSUE THREAD

**Issue by jaraco** [peopledoc/workalendar#607]
The ical tests are failing on Windows with this error:

```
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\failed_ical_tests\\NormalShiftUnitedStatesExceptions_3b_35uoh.ics'
```

It occurs at [this line](https://github.com/peopledoc/workalendar/blob/b3faced4cd87f04bef30b331a3ad85c49d782423/workalendar/tests/__init__.py#L120) when the code attempts to remove a file that's in use, an operation that's allowed on Unix but not on Windows.

**Comment by brunobord** [comment]
indeed.
I kinda "knew" this line would eventually be a pain in the neck, one day.

I'm on it.

**Comment by brunobord** [comment]
you may eventually confirm that the tests work locally if you check out this branch: https://github.com/peopledoc/workalendar/pull/615
