### ISSUE TITLE
20/02/2021 was a working day in Taiwan

### ISSUE THREAD

**Issue by EliseEliz** [peopledoc/workalendar#628]
Hi !

The Saturday 20 February was an exceptional Working day in Taiwan but it returns False with the function is_working_day(date(2021,2,20)).

Thank you for your help

**Comment by brunobord** [comment]
Hello. Do you have any source to confirm this day was a working day, please? (not that I don't believe you, it's that I'd like to check out the reasons why, etc - and have an official source to add to the changes)

**Comment by EliseEliz** [comment]
Hello !

On Internet I have this source for example : https://www.tiplo.com.tw/en/ad_in.aspx?nid=338

Thank you for your quick reply !

**Comment by CRTao** [comment]
👋 Hello 
I lived in Taiwan, and yes, we need to work on 20/02/2021.
The reason is that we have a flexible vacation before Chinese New Year.
The following link is the calendar released by government: https://www.dgpa.gov.tw/information?uid=30&pid=10174

**Comment by brunobord** [comment]
oh boy, I've got to rush to make a hotfix release, then.
stay tuned!

**Comment by brunobord** [comment]
and I couldn't help but notice that Sept, 11th will also be a working day. Adding it to the HF

**Comment by brunobord** [comment]
Hotfix Release 15.0.1 has been published on PyPI. 

* https://pypi.org/project/workalendar/15.0.1/
* https://github.com/peopledoc/workalendar/releases/tag/15.0.1

Happy upgrading, everyone ;o)
