### ISSUE TITLE
conda-forge recipe does not include backports.zoneinfo requirement

### ISSUE THREAD

**Issue by zac-yang** [peopledoc/workalendar#635]
Hi, thanks for maintaining this library. We're installing it via conda-forge, into a python 3.8 environment, hence with the 15.x upgrade ran into import errors where backports.zoneinfo was not installed. Maybe worth updating the recipe?

**Comment by brunobord** [comment]
Hi,

I'm not very familiar with conda, and I don't maintain the conda-forge recipe. How could I get more information on Conda and how it works, and where could I find more about this recipe? It's not the first time this... "thing" (?) is mentioned, and I'm puzzled whenever somebody is asking for help.

**Comment by brunobord** [comment]
As far as I can say, it looks like the recipe is maintained here: https://github.com/conda-forge/workalendar-feedstock
Maybe you could open an issue on their repository, instead?

**Comment by zac-yang** [comment]
Thanks @brunobord, will do, didn't realize that might be maintained by a different set of people. Cheers
